### ISSUE TITLE
Non Compatible with iOS 7

### ISSUE THREAD

**Issue by docash59** [JanC/TAPromotee#2]
Is there a chance you could make it compatible with iOS 7?

**Comment by JanC** [comment]
Hi,
I'm using a `UIVisualEffectView` for the blur and it's only iOS 8. I'll look into it

**Comment by JanC** [comment]
done ;)

**Comment by docash59** [comment]
Blimey, that was quick!
Appreciated thank you!

**Comment by JanC** [comment]
cheers, let me know if you use it in a live app

**Comment by docash59** [comment]
I plan to yes, in my app: https://itunes.apple.com/gb/app/social-dummy-create-fake-social/id610088272?mt=8
