### ISSUE TITLE
Can't make purchase using SKStoreProductViewController. Apple Store Purchase works

### ISSUE THREAD

**Issue by Jhonny12345** [JanC/TAPromotee#8]
Hi,

I am using TAPromotee in my project and using iPAD Mini device (iOS 8.3) for testing. It is showing my app and launching SKStoreProductViewController. When I try to make a purchase then it asks to sign in with APPLE id. I am using my existing APPLE id with correct password (tried several times) but I am always getting following error

"The Apple ID you entered couldn't be found or your password is incorrect"

But when I click on "Store" at the Top right corner and try to make a purchase directly on APPLE STORE using the SAME Apple id and password then it always works. But in that case, I had to live my app while I need in-app store purchase without leaving my app.

I am just not sure that SKStoreProductViewController is working or not. **Can you purchase and download an app using SKStoreProductViewController on a device that has ios 8.3+ version? Can you please check and confirm that it is working on any ios version greater than equal to ios 8.3?**

My Apple id belongs to INDIA Store and valid for purchases in INDIA. **Does TAPromotee only work for an apple id that is valid for purchases in US APPLE STORE?**

I tried changing my iPad setting by setting Country= USA and language = US English but it still doesn't work with my apple id as it is valid for INDIA store. I didn't create a new apple id for US store as I think it is against the iTunes policy to use multiple accounts.

**How am i supposed to fix this issue?**

If it is not working on new iOS versions then please fix this issue. If it is somehow restricted to US only purchase then please add in-app app purchase functionality for other countries too.

Please reply.

Thanks.

**Comment by JanC** [comment]
Hi,
If I remember correctly, you cannot complete the purchase using a 'SKProductViewController' when your app is signed with a development certificate. Maybe that is the reason ?

**Comment by Jhonny12345** [comment]
Oh.. I was running my app locally instead of downloading it from Apple store. 

Thanks.
